### ISSUE TITLE
Adding and removing branches/leaves to a leaf node does not behave as expected

### ISSUE THREAD

**Issue by mothnox** [danwipf/Unity3d-Mtree#10]
Attempting to add a branches or leaves to a leaf node appears to do nothing, but when attempting to remove it, it may disconnect other branch and leaf nodes from the trunk, with no way to reconnect them. 
![tree bug 1](https://user-images.githubusercontent.com/52550171/67452472-f26da300-f5e8-11e9-9ba5-5cefbcddd2ea.png)

Attempting to use undo to fix this causes, well, this:
![tree bug 2](https://user-images.githubusercontent.com/52550171/67452490-fac5de00-f5e8-11e9-92ee-ed6cf6453505.png)

**Comment by danwipf** [comment]
Thanks for reporting this! We are aware of this issue, but may not have listed it! 

But it’s on the todo list for v2.2!

**Comment by danwipf** [comment]
removed the option to add anything on a leaf node! (disabled function)
