### ISSUE TITLE
Feature Request : palm tree compatibility 

### ISSUE THREAD

**Issue by Xulain** [danwipf/Unity3d-Mtree#5]
Mtree is quite hard to use for palm trees and could do with some updates to make it more compatible for custom palm fronds.
![489c499fce111864307aad37abda25c0](https://user-images.githubusercontent.com/56063758/66023521-5240c480-e4e9-11e9-82af-3dd19b8d9775.png)
The problem is getting them evenly spaced around the top of trunk with zero length branches. 
![052d489a1cde9ec9739fbaf9695278cc](https://user-images.githubusercontent.com/56063758/66023589-8ddb8e80-e4e9-11e9-859a-d89286a5a751.png)

![b352bdf3ce8e2ae371068895ea8c11cd](https://user-images.githubusercontent.com/56063758/66025566-ae5a1780-e4ee-11e9-93b3-8494655edd3a.png)

A you can see its not very good. Adjusting the start slider can help but is very hit and miss. 

Also the leaf editor could be made more palm frond friendly too. Palm fronds have a thick center branch and smaller stems so the tool needs a separate radius for both and maybe more control on the leafs so could position them in a semi circle at end of branch.

![87eff1cb5a53ad49b2ae45ad4ce81a15](https://user-images.githubusercontent.com/56063758/66025587-bf0a8d80-e4ee-11e9-9b74-a64587b2255e.png)

I think these features would benefit mtree a lot. I would have paid just for a leaf editor that could make palm frond textures as not been able to find anything that does that and been looking over a year now. 
Thanks

**Comment by danwipf** [comment]
palms should work now!
